export const SET_STOCKS = 'stocks/set_stocks'
export const UPDATE_STOCK_PRICE = 'stocks/update_stock_price'
export const SET_HOLDINGS = 'stocks/set_holdings'
export const UPSERT_HOLDING = 'stocks/upsert_holding'
export const CONNECTED = 'stocks/CONNECTED'
export const SET_TRANSACTIONS = 'stocks/set_transactions'